# Generated by juwelier
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Juwelier::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: wagg 1.2.1.pre ruby lib

Gem::Specification.new do |s|
  s.name = "wagg".freeze
  s.version = "1.2.1.pre"

  s.required_rubygems_version = Gem::Requirement.new("> 1.3.1".freeze) if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib".freeze]
  s.authors = ["Guillermo Rodriguez Cano".freeze]
  s.date = "2016-12-22"
  s.description = "This is a nice Meneame crawler".freeze
  s.email = "wschutz@gmail.com".freeze
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    "Gemfile",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "lib/wagg.rb",
    "lib/wagg/crawler/author.rb",
    "lib/wagg/crawler/comment.rb",
    "lib/wagg/crawler/news.rb",
    "lib/wagg/crawler/page.rb",
    "lib/wagg/crawler/tag.rb",
    "lib/wagg/crawler/version.rb",
    "lib/wagg/crawler/vote.rb",
    "lib/wagg/utils/configuration.rb",
    "lib/wagg/utils/constants.rb",
    "lib/wagg/utils/functions.rb",
    "lib/wagg/utils/retriever.rb",
    "test/helper.rb",
    "test/test_wagg.rb",
    "wagg.gemspec"
  ]
  s.homepage = "http://github.com/wileeam/wagg".freeze
  s.licenses = ["MIT".freeze]
  s.rubygems_version = "2.5.2".freeze
  s.summary = "Meneame Dataset Generator".freeze

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<mechanize>.freeze, [">= 0"])
      s.add_runtime_dependency(%q<feedjira>.freeze, [">= 0"])
      s.add_development_dependency(%q<shoulda>.freeze, [">= 0"])
      s.add_development_dependency(%q<rdoc>.freeze, ["~> 3.12"])
      s.add_development_dependency(%q<bundler>.freeze, ["~> 1.0"])
      s.add_development_dependency(%q<juwelier>.freeze, [">= 2.1.1"])
      s.add_development_dependency(%q<simplecov>.freeze, [">= 0"])
    else
      s.add_dependency(%q<mechanize>.freeze, [">= 0"])
      s.add_dependency(%q<feedjira>.freeze, [">= 0"])
      s.add_dependency(%q<shoulda>.freeze, [">= 0"])
      s.add_dependency(%q<rdoc>.freeze, ["~> 3.12"])
      s.add_dependency(%q<bundler>.freeze, ["~> 1.0"])
      s.add_dependency(%q<juwelier>.freeze, [">= 2.1.1"])
      s.add_dependency(%q<simplecov>.freeze, [">= 0"])
    end
  else
    s.add_dependency(%q<mechanize>.freeze, [">= 0"])
    s.add_dependency(%q<feedjira>.freeze, [">= 0"])
    s.add_dependency(%q<shoulda>.freeze, [">= 0"])
    s.add_dependency(%q<rdoc>.freeze, ["~> 3.12"])
    s.add_dependency(%q<bundler>.freeze, ["~> 1.0"])
    s.add_dependency(%q<juwelier>.freeze, [">= 2.1.1"])
    s.add_dependency(%q<simplecov>.freeze, [">= 0"])
  end
end

